name: 'BindPlane OP Action'
description: 'GitHub Action for BindPlane OP.'
author: 'observIQ'

inputs:
  remote_url:
    description: 'The URL that will be used to connect to BindPlane OP'
    required: true
  api_key:
    description: 'The BindPlane OP API key that will be used to authenticate to BindPlane OP'
  username:
    description: 'The BindPlane OP username that will be used to authenticate to BindPlane OP'
  password:
    description: 'The BindPlane OP password that will be used to authenticate to BindPlane OP'
  destination_path:
    description: 'Path to the file which contains the BindPlane destination resources'
  configuration_path:
    description: 'Path to the file which contains the BindPlane configuration resources'
  configuration_output_dir:
    description: 'Path to the directory which will contain the rendered OTEL format of the configuration resources'
  target_branch:
    description: 'Resource apply and OTEL config write back will only happen when this branch is the current branch of the action'
  token:
    description: 'The GitHub token used to authenticate to GitHub when writing OTEL configs back to the repo'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.remote_url }}
    - ${{ inputs.api_key }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.destination_path }}
    - ${{ inputs.configuration_path }}
    - ${{ inputs.configuration_output_dir }}
    - ${{ inputs.target_branch }}
    - ${{ inputs.token }}
